apiVersion: v1
kind: Secret
type: kubernetes.io/tls
metadata:
  name: {{ include "admission-controller.fullname" . }}-tls
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "admission-controller.name" . }}
    helm.sh/chart: {{ include "admission-controller.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  annotations:
    "helm.sh/hook": "pre-install"
    "helm.sh/hook-delete-policy": "before-hook-creation"
data:
{{ ( include "admission-controller.gen-certs" . ) | indent 2 }}

{{- if .Values.image.accessToken }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "admission-controller.fullname" . }}-imagepull
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "admission-controller.name" . }}
    helm.sh/chart: {{ include "admission-controller.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  .dockerconfigjson: {{ .Values.image.accessToken }}
type: kubernetes.io/dockerconfigjson
{{- end }}
