{{- if .Values.global.rbacEnable }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "alameda-ai.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "alameda-ai.name" . }}
    helm.sh/chart: {{ include "alameda-ai.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
{{- end }}
