apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: alameter
spec:
  ports:
  - port: 8999
    targetPort: 8999
    name: alameter
    nodePort: 31000
  selector:
    app: alameter
  sessionAffinity: None
  type: NodePort

