{{- if .Values.image.accessToken }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "datahub.fullname" . }}-imagepull
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "datahub.name" . }}
    helm.sh/chart: {{ include "datahub.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  .dockerconfigjson: {{ .Values.image.accessToken }}
type: kubernetes.io/dockerconfigjson
{{- end }}
